//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ClientApp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientApp.IServerServices")]
    public interface IServerServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/SetUserState", ReplyAction="http://tempuri.org/IServerServices/SetUserStateResponse")]
        void SetUserState(int sessionId, int stateId, int stateCourse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/getTask", ReplyAction="http://tempuri.org/IServerServices/getTaskResponse")]
        Common.Task getTask(int taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetUsers", ReplyAction="http://tempuri.org/IServerServices/GetUsersResponse")]
        Common.User[] GetUsers(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddCoursesFromXml", ReplyAction="http://tempuri.org/IServerServices/AddCoursesFromXmlResponse")]
        bool AddCoursesFromXml(int sessionId, string xmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetTaskGroupGrades", ReplyAction="http://tempuri.org/IServerServices/GetTaskGroupGradesResponse")]
        Common.TaskGroupGrade[] GetTaskGroupGrades(int taskGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/CountReportedTasksForUserInCourse", ReplyAction="http://tempuri.org/IServerServices/CountReportedTasksForUserInCourseResponse")]
        int CountReportedTasksForUserInCourse(int userId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetCourseGrades", ReplyAction="http://tempuri.org/IServerServices/GetCourseGradesResponse")]
        Common.CourseGrade[] GetCourseGrades(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetUserTask", ReplyAction="http://tempuri.org/IServerServices/GetUserTaskResponse")]
        Common.UserTask GetUserTask(int userId, int taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetCourse", ReplyAction="http://tempuri.org/IServerServices/GetCourseResponse")]
        Common.Course GetCourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddUserTask", ReplyAction="http://tempuri.org/IServerServices/AddUserTaskResponse")]
        bool AddUserTask(int sessionId, int userId, int taskId, int grade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetCourseGrade", ReplyAction="http://tempuri.org/IServerServices/GetCourseGradeResponse")]
        Common.GradedCourse GetCourseGrade(int userId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetTaskGroups", ReplyAction="http://tempuri.org/IServerServices/GetTaskGroupsResponse")]
        Common.TaskGroup[] GetTaskGroups(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetTasks", ReplyAction="http://tempuri.org/IServerServices/GetTasksResponse")]
        Common.Task[] GetTasks(int taskGroupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetUsersForCourse", ReplyAction="http://tempuri.org/IServerServices/GetUsersForCourseResponse")]
        Common.User[] GetUsersForCourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetUserFromId", ReplyAction="http://tempuri.org/IServerServices/GetUserFromIdResponse")]
        Common.User GetUserFromId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetCourseAttentandsForCourse", ReplyAction="http://tempuri.org/IServerServices/GetCourseAttentandsForCourseResponse")]
        Common.CourseAttentant[] GetCourseAttentandsForCourse(int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddCourseAttendant", ReplyAction="http://tempuri.org/IServerServices/AddCourseAttendantResponse")]
        int AddCourseAttendant(int sessionId, int userId, int courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/getCourses", ReplyAction="http://tempuri.org/IServerServices/getCoursesResponse")]
        Common.Course[] getCourses(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddTask", ReplyAction="http://tempuri.org/IServerServices/AddTaskResponse")]
        int AddTask(int sessionId, int taskGroupId, string name, int gradeType, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddTaskGroupGrade", ReplyAction="http://tempuri.org/IServerServices/AddTaskGroupGradeResponse")]
        int AddTaskGroupGrade(int sessionId, int taskgroupId, int limit, int value, string gradeName, string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddTaskGroup", ReplyAction="http://tempuri.org/IServerServices/AddTaskGroupResponse")]
        int AddTaskGroup(int sessionId, int courseId, string taskGroupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddCourseGrade", ReplyAction="http://tempuri.org/IServerServices/AddCourseGradeResponse")]
        int AddCourseGrade(int sessionId, int courseId, string gradeName, int limit, string expression);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddCourse", ReplyAction="http://tempuri.org/IServerServices/AddCourseResponse")]
        int AddCourse(int sessionId, string code, string courseName, int period);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetAccessLevel", ReplyAction="http://tempuri.org/IServerServices/GetAccessLevelResponse")]
        int GetAccessLevel(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetTaskReported", ReplyAction="http://tempuri.org/IServerServices/GetTaskReportedResponse")]
        int GetTaskReported(int taskId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/Logout", ReplyAction="http://tempuri.org/IServerServices/LogoutResponse")]
        void Logout(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/UpdateReported", ReplyAction="http://tempuri.org/IServerServices/UpdateReportedResponse")]
        void UpdateReported(int taskId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/Login", ReplyAction="http://tempuri.org/IServerServices/LoginResponse")]
        int Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/GetUser", ReplyAction="http://tempuri.org/IServerServices/GetUserResponse")]
        Common.User GetUser(int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServices/AddUser", ReplyAction="http://tempuri.org/IServerServices/AddUserResponse")]
        int AddUser(int sessionId, Common.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServicesChannel : Client.ClientApp.IServerServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServicesClient : System.ServiceModel.ClientBase<Client.ClientApp.IServerServices>, Client.ClientApp.IServerServices {
        
        public ServerServicesClient() {
        }
        
        public ServerServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetUserState(int sessionId, int stateId, int stateCourse) {
            base.Channel.SetUserState(sessionId, stateId, stateCourse);
        }
        
        public Common.Task getTask(int taskId) {
            return base.Channel.getTask(taskId);
        }
        
        public Common.User[] GetUsers(int sessionId) {
            return base.Channel.GetUsers(sessionId);
        }
        
        public bool AddCoursesFromXml(int sessionId, string xmlString) {
            return base.Channel.AddCoursesFromXml(sessionId, xmlString);
        }
        
        public Common.TaskGroupGrade[] GetTaskGroupGrades(int taskGroupId) {
            return base.Channel.GetTaskGroupGrades(taskGroupId);
        }
        
        public int CountReportedTasksForUserInCourse(int userId, int courseId) {
            return base.Channel.CountReportedTasksForUserInCourse(userId, courseId);
        }
        
        public Common.CourseGrade[] GetCourseGrades(int courseId) {
            return base.Channel.GetCourseGrades(courseId);
        }
        
        public Common.UserTask GetUserTask(int userId, int taskId) {
            return base.Channel.GetUserTask(userId, taskId);
        }
        
        public Common.Course GetCourse(int courseId) {
            return base.Channel.GetCourse(courseId);
        }
        
        public bool AddUserTask(int sessionId, int userId, int taskId, int grade) {
            return base.Channel.AddUserTask(sessionId, userId, taskId, grade);
        }
        
        public Common.GradedCourse GetCourseGrade(int userId, int courseId) {
            return base.Channel.GetCourseGrade(userId, courseId);
        }
        
        public Common.TaskGroup[] GetTaskGroups(int courseId) {
            return base.Channel.GetTaskGroups(courseId);
        }
        
        public Common.Task[] GetTasks(int taskGroupId) {
            return base.Channel.GetTasks(taskGroupId);
        }
        
        public Common.User[] GetUsersForCourse(int courseId) {
            return base.Channel.GetUsersForCourse(courseId);
        }
        
        public Common.User GetUserFromId(int userId) {
            return base.Channel.GetUserFromId(userId);
        }
        
        public Common.CourseAttentant[] GetCourseAttentandsForCourse(int courseId) {
            return base.Channel.GetCourseAttentandsForCourse(courseId);
        }
        
        public int AddCourseAttendant(int sessionId, int userId, int courseId) {
            return base.Channel.AddCourseAttendant(sessionId, userId, courseId);
        }
        
        public Common.Course[] getCourses(int sessionId) {
            return base.Channel.getCourses(sessionId);
        }
        
        public int AddTask(int sessionId, int taskGroupId, string name, int gradeType, int weight) {
            return base.Channel.AddTask(sessionId, taskGroupId, name, gradeType, weight);
        }
        
        public int AddTaskGroupGrade(int sessionId, int taskgroupId, int limit, int value, string gradeName, string expression) {
            return base.Channel.AddTaskGroupGrade(sessionId, taskgroupId, limit, value, gradeName, expression);
        }
        
        public int AddTaskGroup(int sessionId, int courseId, string taskGroupName) {
            return base.Channel.AddTaskGroup(sessionId, courseId, taskGroupName);
        }
        
        public int AddCourseGrade(int sessionId, int courseId, string gradeName, int limit, string expression) {
            return base.Channel.AddCourseGrade(sessionId, courseId, gradeName, limit, expression);
        }
        
        public int AddCourse(int sessionId, string code, string courseName, int period) {
            return base.Channel.AddCourse(sessionId, code, courseName, period);
        }
        
        public int GetAccessLevel(int sessionId) {
            return base.Channel.GetAccessLevel(sessionId);
        }
        
        public int GetTaskReported(int taskId, int userId) {
            return base.Channel.GetTaskReported(taskId, userId);
        }
        
        public void Logout(int sessionId) {
            base.Channel.Logout(sessionId);
        }
        
        public void UpdateReported(int taskId, int userId) {
            base.Channel.UpdateReported(taskId, userId);
        }
        
        public int Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public Common.User GetUser(int sessionId) {
            return base.Channel.GetUser(sessionId);
        }
        
        public int AddUser(int sessionId, Common.User user) {
            return base.Channel.AddUser(sessionId, user);
        }
    }
}
